version: '3.1'
services:
  server:
    container_name: server
    build: .
    restart: always
    command: ./server
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - .http:/var/lib/http
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    container_name: kode_notes
    image: postgres
    restart: always
    ports:
      - "5444:5432"
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: kode_notes
  migrate:
    image: migrate/migrate
    restart: on-failure
    environment:
      TZ: "Europe/Moscow"
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations/", "-database", "postgres://root:root@restaurant-db:5432/restaurant?sslmode=disable", "up"]    